### PR TITLE
feature: Adds button layout to page

### PR DESCRIPTION
**Pull request by ShikakaQuelor**
Tried this neat little script, thought that it could do with a bit more structured layout.

While at it, did some refactoring of data fetching to use a "hook", can later be used for caching if needed.

### CODE REVIEW

**Comment by Schanihbg** [comment]
@ShikakaQuelor Can you merge to develop or base the changes on develop before merging to main?
Need to test it before sending it out to everyone.

**Comment by ShikakaQuelor** [comment]
@Schanihbg 
Done

**Comment by Schanihbg** [comment]
@ShikakaQuelor did you use some linting? It's hard to see what the actual change was

**Comment by ShikakaQuelor** [comment]
@Schanihbg Sorry for that, used the tampermonkey editor at first, somewhere while copying I made tab-indent change

**Comment by Schanihbg** [comment]
Sorry for not checking this earlier, but it was quite nice!
If you want you can do it again in the new structure, feel free to do so.

Closing this for now

**Pull request closed without merging**
